# Generated by Django 6.0.5 on 2026-05-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NGOContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone", models.CharField(max_length=100)),
                ("org_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_hash", models.CharField(max_length=64, unique=True)),
                ("registered_zone", models.CharField(max_length=100)),
                ("landmark", models.TextField(blank=True, default="")),
                ("carrier_name", models.CharField(blank=True, max_length=100)),
                ("network_code", models.CharField(blank=True, max_length=20)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_pulse_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_date", models.DateField()),
                ("incident_time", models.TimeField()),
                (
                    "reporting_channel",
                    models.CharField(
                        choices=[
                            ("Mobile App", "Mobile App"),
                            ("Hotline", "Hotline"),
                            ("Community Center", "Community Center"),
                            ("Dashboard", "Dashboard"),
                            ("SMS", "SMS"),
                            ("USSD", "USSD"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "follow_up_status",
                    models.CharField(
                        choices=[("Ongoing", "Ongoing"), ("Closed", "Closed")],
                        default="Ongoing",
                        max_length=30,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(db_index=True, max_length=100)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("Domestic Violence", "Domestic Violence"),
                            ("Sexual Assault", "Sexual Assault"),
                            ("Harassment", "Harassment"),
                            ("Child Abuse", "Child Abuse"),
                            ("Unknown", "Unknown"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("victim_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "victim_gender",
                    models.CharField(blank=True, default="Unknown", max_length=20),
                ),
                (
                    "perpetrator_relationship",
                    models.CharField(blank=True, default="Unknown", max_length=50),
                ),
                (
                    "support_provided",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-incident_date", "-incident_time"],
                "indexes": [
                    models.Index(
                        fields=["location", "incident_date"],
                        name="incidents_i_locatio_1c1fae_idx",
                    ),
                    models.Index(
                        fields=["severity_level", "follow_up_status"],
                        name="incidents_i_severit_d08355_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustedContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_name", models.CharField(max_length=100)),
                ("relationship", models.CharField(max_length=50)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registered_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_contacts",
                        to="incidents.registereduser",
                    ),
                ),
            ],
        ),
    ]
