# Generated by Django 6.0.5 on 2026-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_hash", models.CharField(db_index=True, max_length=64)),
                ("network_code", models.CharField(blank=True, max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("WAITING_CONFIRM", "Waiting for YES/NO"),
                            ("WAITING_LANDMARK", "Waiting for landmark update"),
                            ("COMPLETED", "Completed"),
                            ("TIMED_OUT", "Timed out"),
                        ],
                        default="WAITING_CONFIRM",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="incident",
            name="last_verified_location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="incident",
            name="location_confidence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HIGH", "High — live GPS or confirmed"),
                    ("MEDIUM", "Medium — user confirmed recently"),
                    ("LOW", "Low — registered fallback only"),
                ],
                default="LOW",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="location_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GPS", "GPS — mobile app"),
                    ("REGISTERED", "Registered fallback"),
                    ("SMS_UPDATE", "Updated via SMS"),
                    ("USSD_UPDATE", "Updated via USSD"),
                ],
                default="REGISTERED",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="registereduser",
            name="last_known_location",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="registereduser",
            name="last_location_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GPS", "GPS"),
                    ("SMS_UPDATE", "SMS Update"),
                    ("USSD_UPDATE", "USSD Update"),
                    ("REGISTERED", "Registered"),
                ],
                default="REGISTERED",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="registereduser",
            name="last_location_update_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
